name: "Make & Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: make-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  maketest:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        task:
          - 02.UTF-encoder

    steps:
      - name: Получение кода и actions
        uses: actions/checkout@v4

      - name: Инсталляция инструментов
        uses: ./.github/actions/install-prerequisites

      - name: Сборка и тесты
        uses: ./.github/actions/make-utest
        with:
          exercise: ${{ matrix.task }}
